name: Create release
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Install nodejs
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '10'
      #     cache: 'npm'
      - name: setup git config
        run: |
          git config user.name "Sunil Joshi"
          git config user.email "sunil.joshi@airfi.aero"
      - name: Bump package version
        run: npm version minor
      - name: Get release version
        run: echo "RELEASE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')" >> $GITHUB_ENV
      - name: Checkout release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: git checkout -b release/${{ env.RELEASE_VERSION }} develop # TODO remove hardcoding and get default branch
      - name: Create CHANGELOG_new
        run: |
          echo "# ${{ env.RELEASE_VERSION }}" > CHANGELOG_new.md
          echo "*PR1*" >> CHANGELOG_new.md
      - name: Add release to CHANGELOG.md
        run: |
          cat CHANGELOG.md > CHANGELOG_old.md
          cat CHANGELOG_new.md CHANGELOG_old.md > CHANGELOG.md
      - name: Add CHANGELOG.md to git
        run: git commit -am "Change log"
      - name: Push release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin release/${{ env.RELEASE_VERSION }}
      - name: Create pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create v${{ env.RELEASE_VERSION }} --generate-notes --target release/${{ env.RELEASE_VERSION }}
          
      
      
